### ISSUE TITLE
Support compressing output files

### ISSUE THREAD

**Issue by gtonkinhill** [jnalanko/Themisto#10]
Thanks for the great tool! Would it be possible to add an option to produce compressed output?  I'm hoping to run Themisto on multiple samples at once but it requires up to 500Gb of disk space per sample to store the output.

**Comment by jnalanko** [comment]
Implemented in 3c3cb198. Output streaming into a .gz file can be enabled with --gzip-output. Note that now the output is not sorted by default anymore. It can be sorted with the option --sort-output. Also added an explanation of the output format to the help text of pseudoalign:

Each line consists of a space-separated list of integers. The first integer specifies the rank of the read in the input file, and the rest of the integers are the identifiers of the colors of the sequences that the read pseudoaligns with. If the program is ran with more than one thread, the output lines are not necessarily in the same order as the reads in the input file.
