### ISSUE TITLE
themisto_tests should always be built in debug mode

### ISSUE THREAD

**Issue by jnalanko** [jnalanko/Themisto#7]
Themisto tests have a ton of asserts to make sure that everything is working correctly. If the tests are built in release mode, then it's compiled so that the asserts are not checked. The tests should always be built in debug mode.

**Comment by tmaklin** [comment]
Should the tests be built at all when compiling in release mode? I can change the build process to always compile tests in debug mode (regardless of the rest of the project) but wonder if there is any need to compile the tests when making release builds.

**Comment by jnalanko** [comment]
No need for tests in release mode I think.
