### ISSUE TITLE
Add option to write unsorted output

### ISSUE THREAD

**Issue by tmaklin** [jnalanko/Themisto#9]
Currently, Themisto seems to first save the pseudoalignments to a temporary file and then sort that file according to the read's number into the final, sorted output. This can take a lot of disk space (2x the output file's size) if the query has many reads, and for some applications it is not necessary to have a sorted pseudoalignment.

**Comment by tmaklin** [comment]
Further thinking about this it might make sense to output the pseudoalignments as unsorted by default, and have the sorting as an option, a separate program, or refer users to use sort from GNU coreutils.

**Comment by jnalanko** [comment]
Implemented in e021bbf. The output can be sorted with the --sort-output option now. The default no sorting.
